default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: arnamond
  password: test # Use the new password you just set
  host: localhost
  port: 5432

development:
  <<: *default
  database: buffer_clone

test:
  <<: *default
  database: buffer_test

production:
  <<: *default
  database: buffer_production
  username: buffer_prod_user
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>